# These are supported funding model platforms

YouTube: https://www.shreyaan.online
github: [ShreyaanVashishtha]
patreon: ShreyaanVashishtha
open_collective: # Replace with a single Open Collective username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
